version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongo-data:/data/db

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - auth
      - event

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    depends_on:
      - mongodb

  event:
    build:
      context: .
      dockerfile: apps/event/Dockerfile
    depends_on:
      - mongodb

volumes:
  mongo-data:
